[package]
name = "rtee"
version = "0.2.2"
authors = ["Gary Pennington <garypen@gmail.com>"]
description = "tee, but rustee"
license = "MIT OR Apache-2.0"

[dependencies]

clap = "^2.32.0"
nix = "^0.13.0"
